name = "CoupledSystems"
uuid = "4b676bd6-8509-44ec-b400-4b24e2871ede"
authors = ["Taylor McDonnell <taylor.golden.mcdonnell@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"

[compat]
DiffResults = "1.0"
SparseDiffTools = "1.13"
FiniteDiff = "2.8"
ForwardDiff = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
